Another attempt at get_or_create.
The original sql literal stuff here was introduced in #93.  We're now
hitting production issues with it, like this:

```python
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work
self.consume(message)
File "/usr/lib/python2.7/site-packages/datanommer/consumer/__init__.py", line 57, in consume
datanommer.models.add(message)
File "/usr/lib/python2.7/site-packages/datanommer/models/__init__.py", line 166, in add
User.get_or_create(username)
File "/usr/lib/python2.7/site-packages/datanommer/models/__init__.py", line 292, in get_or_create
session.execute(insert)
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
return getattr(self.registry(), name)(*args, **kwargs)
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 991, in execute
bind, close_with_result=True).execute(clause, params or {})
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
return meth(self, multiparams, params)
File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 978, in _execute_context
context._fetch_implicit_returning(result)
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 815, in _fetch_implicit_returning
ipk.append(row[c])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The approach here was inspired by this post:  http://skien.cc/blog/2014/01/15/sqlalchemy-and-race-conditions-implementing/

It tries to retrieve, if that fails it tries to create, and if that
fails it tries to retrieve again.  This feels simpler.